### ISSUE TITLE
How to ignore some fields of a document while checking?

### ISSUE THREAD

**Issue by dtelyukh** [go-kivik/kivikmock#79]
I want to check putting of a document `ExpectPut().WithDoc()`, which has field `lastUpdatedAt` with current timestamp. I don't need to check this field. How can I do partial checking of the document?

**Comment by flimzy** [comment]
That's a good question. It's a use-case I had not explicitly considered before, so there's no direct support for that right now.

The two options I can think of:

1. Find a way to set the `lastUpdatedAt` value to match your test.
2. Instead of `WithDoc`, use the [WillExecute](https://pkg.go.dev/github.com/go-kivik/kivikmock/v3?tab=doc#ExpectedPut.WillExecute) method to write a custom test, that considers only the fields you desire.

**Comment by dtelyukh** [comment]
OK, thanks
